### ISSUE TITLE
Jobs marked failed, unable to download

### ISSUE THREAD

**Issue by avsmith** [lukfor/imputationbot#1]
Trying to download jobs from imputationserver.sph.umich.edu with imputation bot sometimes results in an error:

`Error: 400 - File could not be downloaded. Job execution was not successfull.`

The job has been completed successfully, and can be downloaded with links given on the webpage.

I do not have a reproducible bug to induce this behavior, but have observed it several times.

**Comment by lukfor** [comment]
Fixed in v0.8.2
