### ISSUE TITLE
Trouble compiling from source

### ISSUE THREAD

**Issue by yfarjoun** [lukfor/imputationbot#18]
I'm trying to fix the recursion issue in #16 but am having trouble compiling from source. In particular, there's a mvn library that I'm "forbidden" from downloading:

```
Could not transfer artifact genepi:genepi-io:pom:1.0.12 from/to bintray-genepi-maven (https://dl.bintray.com/genepi/maven): Authorization failed for https://dl.bintray.com/genepi/maven/genepi/genepi-io/1.0.12/genepi-io-1.0.12.pom 403 Forbidden
```

and this is currently blocking my ability to test the changes I made (#17) 

I've submitted the PR anyway, but I'd love to be able to check that my code works ...

**Comment by lukfor** [comment]
Thank you. I updated the maven repository since bintray was shut down.
