### ISSUE TITLE
Max download error when trying to download

### ISSUE THREAD

**Issue by avsmith** [lukfor/imputationbot#2]
Trying to download jobs from imputationserver.sph.umich.edu with imputation bot sometimes results in an error:

`Error: 400 - File could not be downloaded. Max download limit exceeded.`

The job has been completed successfully, and can be downloaded with links given on the webpage. Reseting the download counter does not fix the behavior.

I do not have a reproducible bug to induce this behavior, but have observed it multiple times.

**Comment by lukfor** [comment]
Fixed in v0.8.2
