### ISSUE TITLE
Michigan API token only valid for a couple of hours.

### ISSUE THREAD

**Issue by alkaZeltser** [lukfor/imputationbot#30]
When updating the API token for a Michigan Imputation Server instance, the expiry date was set to only a of couple hours from the time of update. Previously tokens would last for 30 days. Not sure if this is an imputation bot issue or a Server issue.

`imputationbot add-instance`

`Imputation Bot is ready to submit jobs to https://imputationserver.sph.umich.edu (Genotype Imputation (Minimac4)) 1.7.3)`

`Warning! Your API Token expires in 0 days`

Instance created Fri Jun 16 18:15:19 PDT 2023 
Instance expired Fri Jun 16 21:15:19 EDT 2023

**Comment by lukfor** [comment]
Thanks for reporting this issue! 👍 
It was a server issue and is fixed now. We let you know as soon as the new version is online.

**Comment by alkaZeltser** [comment]
Token is now updating as expected, thank you!
